# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Bot

on:
  workflow_dispatch:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: install required packages
      run: |
        sudo apt-get update
        sudo apt-get install ffmpeg -y
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Bot
      run: |
        python bot.py & python youtubedl.py
      env:
       DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
       CALENDAR_TOKEN: ${{ secrets.CALENDAR_TOKEN }}
       TZ: ${{ secrets.TZ }}
